Repository rezarinaldi/dynahunt, pull requests merged in 2024-03, with the labels that each got.

#5 1 setup boilerplates databases storage and vercel
  src/lib/uploadFile.js
  src/prisma/schema.prisma
Labels: enhancement

#9 3 register UI func
  __apitesting/auth.http
  src/app/(auth)/register/page.js
  src/app/api/v1/auth/register/route.js
  src/components/auth/register.jsx
  src/middleware.js
  src/prisma/schema.prisma
Labels: enhancement

#11 feat: add field phone_number
  __apitesting/auth.http
  src/app/api/v1/auth/register/route.js
  src/components/auth/register.jsx
Labels: enhancement

#12 chore: regenerate prisma
  src/app/api/v1/auth/register/route.js
Labels: enhancement

#14 3 register UI func
  __apitesting/auth.http
  package-lock.json
  package.json
  src/components/auth/register.jsx
Labels: bug, enhancement

#16 docs: update readme & scripts
  README.md
  package.json
Labels: documentation

#17 feat: navbar, hero, footer component
  .gitignore
  __apitesting/auth.http
  package-lock.json
  package.json
  src/app/(landing)/layout.js
  src/app/(landing)/page.js
  src/app/icon.png
  src/app/layout.js
  src/app/page.js
  src/components/Footer.jsx
  src/components/Hero.jsx
  src/components/Home.jsx
  src/components/InfluencerItem.jsx
  src/components/Navbar.jsx
  src/styles/globals.css
Labels: enhancement

#19 feat: Login UI
  src/components/auth/login.jsx
Labels: enhancement

#20 3 register UI func
  .env.example
  package-lock.json
  package.json
  src/app/(landing)/layout.js
  src/app/(landing)/page.js
  src/components/Footer.jsx
  src/components/Hero.jsx
  src/components/InfluencerItem.jsx
  src/components/Navbar.jsx
  src/components/auth/login.jsx
  src/components/auth/register.jsx
Labels: enhancement

#22 style: improved auth ui
  .env.example
  package.json
  src/app/(auth)/login/page.js
  src/app/(auth)/register/page.js
  src/components/auth/login.jsx
  src/components/auth/register.jsx
Labels: enhancement

#25 chore: change color logo
  public/asset.md
  public/img/dh-white.svg
  public/img/dh.svg
  src/app/(auth)/login/page.js
  src/app/(auth)/register/page.js
  src/app/icon.png
  src/app/layout.js
  src/components/auth/Login.jsx
  src/components/auth/Register.jsx
Labels: enhancement

#26 4 home UI
  .gitignore
  README.md
  package-lock.json
  package.json
  public/asset.md
  public/img/campaign/gojek.svg
  public/img/campaign/google.svg
  public/img/campaign/shopee.png
  public/img/campaign/tokopedia.svg
  public/img/campaign/traveloka.svg
  public/img/dh-white.svg
  public/img/dh.svg
  public/img/instagram.svg
  src/app/(auth)/login/page.js
  src/app/(auth)/register/page.js
  src/app/(landing)/layout.js
  src/app/(landing)/page.js
  src/app/api/v1/auth/login/route.js
  src/app/api/v1/auth/register/route.js
  src/app/api/v1/influencer/[influencer_id]/route.js
  src/app/api/v1/influencer/route.js
  src/app/api/v1/interest/[influencer_id]/[interest_id]/route.js
  src/app/api/v1/interest/[influencer_id]/route.js
  src/app/icon.png
  src/app/layout.js
  src/app/page.js
  src/components/Campaign.jsx
  src/components/Filtering.jsx
  src/components/Footer.jsx
  src/components/Hero.jsx
  src/components/Home.jsx
  src/components/InfluencerItem.jsx
  src/components/Navbar.jsx
  src/components/auth/Login.jsx
  src/components/auth/Register.jsx
  src/middleware.js
  src/prisma/schema.prisma
  src/styles/globals.css
Labels: enhancement

#28 chore: update auth func
  package-lock.json
  package.json
  src/app/(landing)/page.js
  src/app/api/v1/auth/login/route.js
  src/app/layout.js
  src/components/Navbar.jsx
  src/components/auth/Login.jsx
  src/components/auth/Register.jsx
  src/lib/providerToast.jsx
  src/middleware.js
Labels: enhancement

#30 chore: update navbar, img campaigns
  public/img/campaign/antv.png
  public/img/campaign/gojek.svg
  public/img/campaign/google.svg
  public/img/campaign/indosiar.png
  public/img/campaign/metrotv.png
  public/img/campaign/mnctv.png
  public/img/campaign/rcti.png
  public/img/campaign/shopee.png
  public/img/campaign/tokopedia.svg
  public/img/campaign/trans7.png
  public/img/campaign/traveloka.svg
  src/components/Campaign.jsx
  src/components/Hero.jsx
  src/components/InfluencerItem.jsx
  src/components/Navbar.jsx
  src/components/auth/Login.jsx
Labels: enhancement

#31 feat: sidebar, header, menu, btn log out
  package-lock.json
  package.json
  src/app/influencer/layout.js
  src/app/influencer/page.js
  src/components/Navbar.jsx
  src/components/influencer/Header.jsx
  src/components/influencer/Profile.jsx
  src/components/influencer/Sidebar.jsx
Labels: enhancement

#41 chore: update lib toast, add lib sosmed embed
  package-lock.json
  package.json
  public/img/campaign/gojek.svg
  public/img/campaign/indosiar.png
  public/img/campaign/metrotv.png
  public/img/campaign/mnctv.png
  public/img/campaign/tokopedia.png
  public/img/campaign/yamaha.png
  src/app/layout.js
  src/components/Campaign.jsx
  src/components/Navbar.jsx
  src/components/auth/Login.jsx
  src/components/auth/Register.jsx
  src/components/influencer/Sidebar.jsx
  src/lib/providerToast.jsx
  src/lib/toast.js
Labels: enhancement, setup

#42 feat: management profile page ui
  src/app/influencer/manage/page.js
  src/components/influencer/ManageProfile.jsx
  src/components/influencer/ProfileForm.jsx
  src/components/influencer/Sidebar.jsx
Labels: enhancement, styling

#43 feat: offered campaigns page ui
  src/app/influencer/offer/page.js
  src/components/influencer/CampaignItem.jsx
  src/components/influencer/OfferCampaigns.jsx
  src/components/influencer/Sidebar.jsx
Labels: enhancement, styling

#44 fix: moved user data to component
  src/app/(landing)/page.js
  src/components/Navbar.jsx
  src/components/influencer/CampaignItem.jsx
  src/components/influencer/Header.jsx
  src/components/influencer/Profile.jsx
  src/components/influencer/ProfileItem.jsx
Labels: bug, enhancement

#45 style: profile influencer ui page
  public/img/campaign/zayn.jpeg
  src/components/Navbar.jsx
  src/components/influencer/EmbedItem.jsx
  src/components/influencer/ManageProfile.jsx
  src/components/influencer/Profile.jsx
  src/components/influencer/ProfileItem.jsx
Labels: enhancement, styling

#46 bug: adding fetching user, but still not found
  .env.example
  src/app/(landing)/page.js
  src/app/api/v1/influencer/route.js
  src/components/Hero.jsx
  src/components/Influencer.jsx
  src/components/InfluencerItem.jsx
  src/components/Landing.jsx
  src/components/config/fetch.js
  src/components/influencer/EmbedItem.jsx
  src/components/influencer/Profile.jsx
  src/components/influencer/ProfileItem.jsx
Labels: bug, styling, functionality

#47 fix: hide fetching function
  src/app/(landing)/page.js
  src/components/Influencer.jsx
  src/components/Landing.jsx
Labels: bug, functionality

#48 feat: adding modal for interest collab
  src/components/InfluencerItem.jsx
Labels: enhancement, functionality

#50 update home and profile page
  public/img/campaign/zayn.jpeg
  public/img/fotoprofil/angga.jpg
  public/img/fotoprofil/ansel.jpg
  public/img/fotoprofil/azizah.jpg
  public/img/fotoprofil/daddy.jpg
  public/img/fotoprofil/deddy.jpg
  public/img/fotoprofil/fuji.jpg
  public/img/fotoprofil/iqbal.jpg
  public/img/fotoprofil/malaikha.jpg
  public/img/fotoprofil/pev.jpg
  public/img/fotoprofil/raffi.jpg
  src/components/InfluencerItem.jsx
  src/components/influencer/EmbedItem.jsx
  src/components/influencer/ProfileItem.jsx
Labels: enhancement, styling
